---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_cfg_path: test/vagrant/ansible.cfg
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  # require_chef_omnibus: false
  require_ansible_omnibus: true
  # require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: centos-8
  - name: centos-7
  # - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
  - name: default-scan
    run_list:
    attributes:
  - name: default-v3
    run_list:
    attributes:
