---

## https://github.com/volatilityfoundation/volatility/wiki/Memory-Samples
## https://code.google.com/p/volatility/wiki/SampleMemoryImages

- name: Ensure volatility samples directory exists
  ansible.builtin.file:
    dest: "{{ volatility_installdir }}/samples"
    state: directory
    mode: '0755'

- name: Download memory samples
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ volatility_installdir }}/samples"
    mode: '0600'
  with_items:
    # - http://www.cfreds.nist.gov/mem/memory-images.rar
    # - http://malwarecookbook.googlecode.com/svn-history/r26/trunk/17/1/zeus.vmem.zip
    # - http://www.mediafire.com/file/yxqodp1p2aca91x/0zapftis.rar
    # - http://malwarecookbook.googlecode.com/svn-history/r26/trunk/17/11/sality.vmem.zip
    ## 404
    # - http://malwarecookbook.googlecode.com/svn-history/r26/trunk/17/1/zeus.vmem.zip
    # - http://malwarecookbook.googlecode.com/svn-history/r26/trunk/17/6/be2.vmem.zip
    # - http://amnesia.gtisc.gatech.edu/%7Emoyix/ds_fuzz_hidden_proc.img.bz2
    - http://www.jonrajewski.com/data/Malware/stuxnet.vmem.zip

- name: Add unrar to unarchive
  ansible.builtin.package:
    name: "{{ unrar_pkg }}"
    state: "present"
  register: pkg_result
  until: pkg_result is success
