---

- name: Set fact pip_url HEAD
  set_fact:
    #pip_url: https://github.com/volatilityfoundation/volatility.git
    pip_url: https://github.com/volatilityfoundation/volatility/archive/master.tar.gz
  when: volatility_release == 'HEAD'
- name: Set fact pip_url non-HEAD
  set_fact:
    pip_url: https://github.com/volatilityfoundation/volatility/archive/{{ volatility_release }}.tar.gz
  when: volatility_release != 'HEAD'

- block:
    - name: install volatility pip dependencies
      pip:
        name: "{{ volatility_pip_pkg }}"
        state: present
      register: pkg_result
      until: pkg_result is success

    - name: install volatility
      pip:
        name: "{{ pip_url }}"
        state: present
        executable: "{{ pip_bin | default('pip') }}"
      register: pkg_result
      until: pkg_result is success
  when: not volatility_virtualenv
- block:
    - name: ensure virtualenv is present
      package:
        name: python-virtualenv
        state: present
      register: pkg_result
      until: pkg_result is success
    - name: install volatility pip dependencies - virtualenv
      pip:
        name: "{{ [ 'setuptools', 'pip', 'pycrypto' ] + volatility_pip_pkg }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: install volatility - virtualenv
      pip:
        name: "{{ pip_url }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: symlink volatility in usual path
      file:
        src: "{{ volatility_virtualenv }}/bin/vol.py"
        dest: "{{ vol_bin_path }}"
        state: link
  when: volatility_virtualenv != ''

- name: ensure git is present
  package: name=git state=present
  register: pkg_result
  until: pkg_result is success

- name: Volatility profiles
  git:
    repo: https://github.com/volatilityfoundation/profiles.git
    dest: "{{ volatility_installdir }}/profiles"
    version: "{{ volatility_profiles_version | default('524a5340bbf48f4a6f48d344d2554fdf65f6c1d4') }}"
