---

- name: ensure volatility plugins directory exists
  file: dest={{ volatility_installdir }}/volatilityplugins mode=0755 state=directory

## most of https://github.com/sans-dfir/sift-files/tree/master/volatility should be here
- name: Volatility plugins developed and maintained by the community
  git: repo=https://github.com/volatilityfoundation/community.git
       dest={{ volatility_installdir }}/volatilityplugins/community

- name: editbox - extracts the text from Windows Edit controls
  git: repo=https://github.com/bridgeythegeek/editbox.git
       dest={{ volatility_installdir }}/volatilityplugins/editbox

- name: malware config extractor - plugx, andromeda
  git: repo=https://github.com/arbor-jjones/volatility_plugins.git
       dest={{ volatility_installdir }}/volatilityplugins/plugx+andromeda

- name: autoruns
  git: repo=https://github.com/tomchop/volatility-autoruns
       dest={{ volatility_installdir }}/volatilityplugins/volatility-autoruns

- name: bitlocker keys retrieving
  git: repo=https://github.com/elceef/bitlocker
       dest={{ volatility_installdir }}/volatilityplugins/elceef-bitlocker

## http://blog.jpcert.or.jp/2016/12/a-new-tool-to-d-d6bc.html
- name: Artifact Analysis tool from JP-CERT
  git: repo=https://github.com/JPCERTCC/aa-tools.git
       dest={{ volatility_installdir }}/volatilityplugins/aa-tools

- stat: path=/usr/lib/python2.7/dist-packages/volatility/plugins
  register: plugins1
- stat: path=/usr/local/lib/python2.7/dist-packages/volatility/plugins
  register: plugins2
- set_fact:
    vol_plugins: /usr/lib/python2.7/dist-packages/volatility/plugins
  when: plugins1.stat.exists
- set_fact:
    vol_plugins: /usr/local/lib/python2.7/dist-packages/volatility/plugins
  when: plugins2.stat.exists

- stat: path="{{ vol_plugins }}/autoruns.py"
  register: autoruns
  when: vol_plugins is defined
- name: map autoruns in volatility plugins tree
  file:
    src: "{{ volatility_installdir }}/volatilityplugins/volatility-autoruns/autoruns.py"
    dest: "{{ vol_plugins }}/autoruns.py"
    state: link
  when: vol_plugins is defined and not autoruns.stat.exists

