---

## https://digital-forensics.sans.org/media/Poster-2015-Memory-Forensics.pdf
## https://volatility-labs.blogspot.ca/2016/08/automating-detection-of-known-malware.html

- name: ensure clamav is installed
  ansible.builtin.package: name=clamav state=present
  register: pkg_result
  until: pkg_result is success

- name: ensure target directories exist
  ansible.builtin.file: dest={{ item }} state=directory mode=0755
  with_items:
    - "{{ volatility_scan_remote_path | dirname }}"
    - "{{ volatility_scan_outdir }}"
    - "{{ volatility_scan_outdir }}/dlldump"
    - "{{ volatility_scan_outdir }}/malfind"
    - "{{ volatility_scan_outdir }}/moddump"

- name: push file to analyze from orchestrator
  ansible.builtin.copy:
    src: "{{ volatility_scan_orchestrator_src }}"
    dest: "{{ volatility_scan_remote_path }}"
    mode: '0600'
    remote_src: "{{ volatility_scan_remote }}"
  when: volatility_remote_src is defined and volatility_remote_src

- name: uncompress file to analyze
  ansible.builtin.unarchive:
    src: "{{ volatility_scan_remote_path }}"
    dest: "{{ volatility_scan_remote_path | dirname }}"
    mode: '0600'
  when: volatility_scan_unarchive

- name: execute volatility psxview
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} psxview |
        tee {{ volatility_scan_outdir }}/psxview.txt
  args:
    creates: "{{ volatility_scan_outdir }}/psxview.txt"
    executable: /bin/bash

- name: execute volatility dlllist
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} dlllist |
        tee {{ volatility_scan_outdir }}/dlllist.txt
  args:
    creates: "{{ volatility_scan_outdir }}/dlllist.txt"
    executable: /bin/bash

- name: execute volatility dlldump
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} dlldump —memory -D {{ volatility_scan_outdir }}/dlldump |
        tee {{ volatility_scan_outdir }}/dlldump.txt
  args:
    creates: "{{ volatility_scan_outdir }}/dlldump.txt"
    executable: /bin/bash

- name: execute volatility malfind
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} malfind -D {{ volatility_scan_outdir }}/malfind |
        tee {{ volatility_scan_outdir }}/malfind.txt
  args:
    creates: "{{ volatility_scan_outdir }}/malfind.txt"
    executable: /bin/bash

- name: execute volatility moddump
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} moddump —memory -D {{ volatility_scan_outdir }}/moddump |
        tee {{ volatility_scan_outdir }}/moddump.txt
  args:
    creates: "{{ volatility_scan_outdir }}/moddump.txt"
    executable: /bin/bash

- name: check file types of volatility output
  ansible.builtin.shell: |
    set -o pipefail
    file {{ volatility_scan_outdir }}/* | egrep -i '(PE32 executable|UPX compressed|data)' |
        tee {{ volatility_scan_outdir }}/file.txt
  args:
    creates: "{{ volatility_scan_outdir }}/file.txt"
    executable: /bin/bash

- name: execute clamscan on extracted file
  ansible.builtin.command: >
    clamscan -ir -l {{ volatility_scan_outdir }}/clamscan.txt {{ volatility_scan_outdir }}/
  args:
    creates: "{{ volatility_scan_outdir }}/clamscan.txt"
  failed_when: false

- name: execute volatility netscan
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} netscan |
        tee {{ volatility_scan_outdir }}/netscan.txt
  args:
    creates: "{{ volatility_scan_outdir }}/netscan.txt"
    executable: /bin/bash

- name: execute volatility ssdt
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} ssdt |
        tee {{ volatility_scan_outdir }}/ssdt.txt
  args:
    creates: "{{ volatility_scan_outdir }}/ssdt.txt"
    executable: /bin/bash
- name: match ntosk|win32k
  ansible.builtin.command: "egrep -v '(ntosk|win32k)' {{ volatility_scan_outdir }}/ssdt.txt"
  changed_when: false
  failed_when: false

- name: execute volatility usnparser
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} usnparser --output=csv
        --output-file={{ volatility_scan_outdir }}/usn.csv -CS |
        tee {{ volatility_scan_outdir }}/usnparser.txt
  args:
    creates: "{{ volatility_scan_outdir }}/usnparser.txt"
    executable: /bin/bash

- name: execute volatility autoruns
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} autoruns -t autoruns |
        tee {{ volatility_scan_outdir }}/autoruns.txt
  args:
    creates: "{{ volatility_scan_outdir }}/autoruns.txt"
    executable: /bin/bash

- name: execute volatility ethscan (pcap recovery)
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} ethscan --save-pcap={{ volatility_scan_outdir }}/out.pcap |
        tee {{ volatility_scan_outdir }}/ethscan.txt
  args:
    creates: "{{ volatility_scan_outdir }}/ethscan.txt"
    executable: /bin/bash

- name: execute volatility netscan (vista+)
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} netscan |
        tee {{ volatility_scan_outdir }}/netscan.txt
  args:
    creates: "{{ volatility_scan_outdir }}/netscan.txt"
    executable: /bin/bash

- name: execute volatility mimikatz
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} mimikatz |
        tee {{ volatility_scan_outdir }}/mimikatz.txt
  args:
    creates: "{{ volatility_scan_outdir }}/mimikatz.txt"
    executable: /bin/bash

- name: execute volatility firefoxhistory
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} firefoxhistory --output=csv
        --output-file={{ volatility_scan_outdir }}/firefox.csv |
        tee {{ volatility_scan_outdir }}/firefoxhistory.txt
  args:
    creates: "{{ volatility_scan_outdir }}/firefoxhistory.txt"
    executable: /bin/bash

- name: execute volatility consoles
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} consoles |
        tee {{ volatility_scan_outdir }}/consoles.txt
  args:
    creates: "{{ volatility_scan_outdir }}/consoles.txt"
    executable: /bin/bash

- name: execute volatility cmdscan
  ansible.builtin.shell: |
    set -o pipefail
    vol.py -f {{ volatility_scan_remote_path | dirname }}/{{ volatility_scan_file }}
        --profile={{ volatility_scan_profile }} cmdscan |
        tee {{ volatility_scan_outdir }}/cmdscan.txt
  args:
    creates: "{{ volatility_scan_outdir }}/cmdscan.txt"
    executable: /bin/bash

- name: check results
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "ls -lh {{ volatility_scan_outdir }}"
    - "cat {{ volatility_scan_outdir }}/psxview.txt"
    - "cat {{ volatility_scan_outdir }}/clamscan.txt"
  changed_when: false
  register: out
- name: Debug | results output
  ansible.builtin.debug: var=out

## wipe ? encrypt/sign archive? do on trusted computer anyway.

- name: pull
  block:
    - name: archive output content
      ansible.builtin.archive:
        src: "{{ volatility_scan_outdir }}"
        dest: "/tmp/volatility-scan-{{ volatility_scan_file | basename }}.tar.gz"
        mode: '0600'
    - name: retrieve output dir to orchestrator
      ansible.builtin.fetch: "src={{ item }} dest={{ volatility_scan_pulldir }}/"
      with_items:
        - "/tmp/volatility-scan-{{ volatility_scan_file | basename }}.tar.gz"
  when: volatility_scan_pull is defined and volatility_scan_pull
