---

- name: Ensure volatility plugins directory exists
  ansible.builtin.file:
    dest: "{{ volatility_installdir }}/volatility3plugins"
    mode: '0755'
    state: directory

- name: Autoruns
  ansible.builtin.git:
    repo: https://github.com/Telindus-CSIRT/volatility3-autoruns
    dest: "{{ volatility_installdir }}/volatility3plugins/volatility-autoruns"
    version: "{{ vol3_autoruns_version }}"

- name: Check volatility plugins directory 1
  ansible.builtin.stat:
    path: /usr/lib/python3.6/dist-packages/volatility/plugins
  register: plugins1
- name: Check volatility plugins directory 1
  ansible.builtin.stat:
    path: /usr/local/lib/python3.6/dist-packages/volatility/plugins
  register: plugins2
- name: Set fact volatility plugins directory 1
  ansible.builtin.set_fact:
    vol_plugins: /usr/lib/python3.8/dist-packages/volatility/plugins
  when: plugins1.stat.exists
- name: Set fact volatility plugins directory 2
  ansible.builtin.set_fact:
    vol_plugins: /usr/local/lib/python3.8/dist-packages/volatility/plugins
  when: plugins2.stat.exists

- name: Check if autoruns plugin is present
  ansible.builtin.stat:
    path: "{{ vol_plugins }}/autoruns.py"
  register: autoruns
  when: vol_plugins is defined
- name: Map autoruns in volatility plugins tree
  ansible.builtin.file:
    src: "{{ volatility_installdir }}/volatility3plugins/volatility-autoruns/autoruns.py"
    dest: "{{ vol_plugins }}/autoruns.py"
    mode: '0644'
    state: link
  when: vol_plugins is defined and not autoruns.stat.exists
