---

- name: Set fact pip_url HEAD
  ansible.builtin.set_fact:
    # pip_url: https://github.com/volatilityfoundation/volatility.git
    pip_url: https://github.com/volatilityfoundation/volatility/archive/master.tar.gz
  when: volatility_release == 'HEAD'
- name: Set fact pip_url non-HEAD
  ansible.builtin.set_fact:
    pip_url: https://github.com/volatilityfoundation/volatility/archive/{{ volatility_release }}.tar.gz
  when: volatility_release != 'HEAD'
- name: Enforce python2
  ansible.builtin.set_fact:
    python_bin: python
    pip_bin: pip
- name: RedHat 8 | Enforce python2
  ansible.builtin.set_fact:
    python_bin: python2
    pip_bin: pip2
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '8'

- name: Install python dependencies
  ansible.builtin.package: name={{ python2_deps }} state=present
  register: pkg_result
  until: pkg_result is success

- name: System pip
  block:
    - name: Install setuptools pip dependencies - python2
      ansible.builtin.pip:
        name: setuptools
        version: 44.0.0
        state: present
      register: pkg_result
      until: pkg_result is success

    - name: Install volatility pip dependencies
      ansible.builtin.pip:
        name: "{{ volatility_pip_pkg }}"
        state: present
      register: pkg_result
      until: pkg_result is success

    - name: Install volatility
      ansible.builtin.pip:
        name: "{{ pip_url }}"
        state: present
        executable: "{{ pip_bin | default('pip') }}"
      register: pkg_result
      until: pkg_result is success
  when: not volatility_virtualenv
- name: Virtualenv pip
  block:
    - name: Ensure virtualenv is present
      ansible.builtin.package:
        name: "{{ python_virtualenv_pkg | default('python-virtualenv') }}"
        state: present
      register: pkg_result
      until: pkg_result is success

    - name: Install setuptools pip dependencies - python2 - virtualenv
      ansible.builtin.pip:
        name: setuptools
        version: 44.0.0
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    # 3.5.0: error: ‘for’ loop initial declarations are only allowed in C99 mode
    - name: Centos7 | force distorm3 3.4.4 - virtualenv
      ansible.builtin.pip:
        name: distorm3
        version: 3.4.4
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

    - name: Install volatility pip dependencies - virtualenv
      ansible.builtin.pip:
        name: "{{ ['pip', 'pycrypto'] + volatility_pip_pkg }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: Install volatility - virtualenv
      ansible.builtin.pip:
        name: "{{ pip_url }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: Symlink volatility in usual path
      ansible.builtin.file:
        src: "{{ volatility_virtualenv }}/bin/vol.py"
        dest: "{{ vol_bin_path }}"
        mode: '0755'
        state: link
  when: volatility_virtualenv | string

- name: Ensure git is present
  ansible.builtin.package: name=git state=present
  register: pkg_result
  until: pkg_result is success

- name: Volatility profiles
  ansible.builtin.git:
    repo: https://github.com/volatilityfoundation/profiles.git
    dest: "{{ volatility_installdir }}/profiles"
    version: "{{ volatility_profiles_version | default('1c6bde858855c6ac6a3a0691ece3af65afb877e6') }}"

- import_tasks: volatility-modules.yml
