---

- name: Set fact pip_url HEAD
  ansible.builtin.set_fact:
    # pip_url: https://github.com/volatilityfoundation/volatility.git
    pip_url: "git+https://github.com/volatilityfoundation/volatility3.git{% if _volatility_release is defined %}@v{{ _volatility_release }}{% endif %}"
  when: volatility_release == 'HEAD'
- name: Set fact pip_url non-HEAD
  ansible.builtin.set_fact:
    pip_url: volatility3
  when: volatility_release != 'HEAD'

- name: Install git and python dependencies
  ansible.builtin.package:
    name: "{{ python_deps }}"
    state: "present"
  register: pkg_result
  until: pkg_result is success

- name: Ensure volatility install directory exists
  ansible.builtin.file:
    dest: "{{ volatility_installdir }}"
    mode: '0755'
    state: directory

- name: System pip3
  when: not volatility_virtualenv
  block:
    - name: Copy volatility3 requirements
      ansible.builtin.copy:
        src: requirements-volatility3.txt
        dest: "{{ volatility_installdir }}/requirements-volatility3.txt"
        mode: '0600'
    - name: Ensure volatility3 and pip3 dependencies present
      ansible.builtin.pip:
        requirements: "{{ volatility_installdir }}/requirements-volatility3.txt"
        executable: "{{ pip_bin | default('pip3') }}"
      register: pkg_result
      until: pkg_result is success

- name: Virtualenv pip3
  when: volatility_virtualenv | length > 0
  block:
    - name: Ensure virtualenv is present
      ansible.builtin.package:
        name: "{{ python_virtualenv_pkg | default('python-virtualenv') }}"
        state: present
      register: pkg_result
      until: pkg_result is success

    - name: Copy venv requirements
      ansible.builtin.template:
        src: requirements-venv.txt.j2
        dest: "{{ volatility_installdir }}/requirements-venv.txt"
        mode: '0600'
    - name: Ensure volatility3 and pip3 dependencies present
      ansible.builtin.pip:
        requirements: "{{ volatility_installdir }}/requirements-venv.txt"
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success
    - name: Copy volatility3 requirements
      ansible.builtin.copy:
        src: requirements-volatility3.txt
        dest: "{{ volatility_installdir }}/requirements-volatility3.txt"
        mode: '0600'
    - name: Ensure volatility3 and pip3 dependencies present
      ansible.builtin.pip:
        requirements: "{{ volatility_installdir }}/requirements-volatility3.txt"
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: Symlink volatility in usual path
      ansible.builtin.file:
        src: "{{ volatility_virtualenv }}/bin/vol"
        dest: "{{ vol_bin_path }}"
        mode: '0755'
        state: link

    - name: Ensure symbols directory writable by all users
      ansible.builtin.file:
        path: "{{ volatility_virtualenv }}/lib/python3.8/site-packages/volatility3/symbols/windows"
        state: directory
        mode: '1777'

- name: Ensure git is present
  ansible.builtin.package:
    name: git
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Import volatility3-modules
  ansible.builtin.import_tasks: volatility3-modules.yml
