---

- name: Set fact pip_url HEAD
  set_fact:
    # pip_url: https://github.com/volatilityfoundation/volatility.git
    pip_url: git+https://github.com/volatilityfoundation/volatility3.git
  when: volatility_release == 'HEAD'
- name: Set fact pip_url non-HEAD
  set_fact:
    pip_url: volatility3
  when: volatility_release != 'HEAD'

- name: install git and python dependencies
  package: name={{ python_deps }} state=present
  register: pkg_result
  until: pkg_result is success

- block:
    - name: install volatility3 pip dependencies
      pip:
        name: "{{ volatility3_pip_pkg }}"
        state: present
      register: pkg_result
      until: pkg_result is success

    - name: install volatility3
      pip:
        name: "{{ pip_url }}"
        state: present
        executable: "{{ pip_bin | default('pip') }}"
      register: pkg_result
      until: pkg_result is success
  when: not volatility_virtualenv
- block:
    - name: ensure virtualenv is present
      package:
        name: "{{ python_virtualenv_pkg | default('python-virtualenv') }}"
        state: present
      register: pkg_result
      until: pkg_result is success
    - name: install volatility3 pip dependencies - virtualenv
      pip:
        name: "{{ [ 'setuptools', 'pip' ] + volatility3_pip_pkg }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: install volatility3 - virtualenv
      pip:
        name: "{{ pip_url }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: symlink volatility in usual path
      file:
        src: "{{ volatility_virtualenv }}/bin/vol"
        dest: "{{ vol_bin_path }}"
        mode: '0755'
        state: link

    - name: Ensure symbols directory writable by all users
      file:
        path: "{{ volatility_virtualenv }}/lib/python3.8/site-packages/volatility3/symbols/windows"
        state: directory
        mode: '1777'
  when: volatility_virtualenv|string

- name: ensure git is present
  package: name=git state=present
  register: pkg_result
  until: pkg_result is success

- include: volatility3-modules.yml
