---

- name: Set fact pip_url HEAD
  ansible.builtin.set_fact:
    # pip_url: https://github.com/volatilityfoundation/volatility.git
    pip_url: git+https://github.com/volatilityfoundation/volatility3.git
  when: volatility_release == 'HEAD'
- name: Set fact pip_url non-HEAD
  ansible.builtin.set_fact:
    pip_url: volatility3
  when: volatility_release != 'HEAD'

- name: Install git and python dependencies
  ansible.builtin.package:
    name: "{{ python_deps }}"
    state: "present"
  register: pkg_result
  until: pkg_result is success

- name: System pip3
  when: not volatility_virtualenv
  block:
    - name: Install volatility3 pip dependencies
      ansible.builtin.pip:
        name: "{{ volatility3_pip_pkg }}"
        state: present
      register: pkg_result
      until: pkg_result is success

    - name: Install volatility3
      ansible.builtin.pip:
        name: "{{ pip_url }}"
        version: "{{ _volatility_release | default(omit) }}"
        state: present
        executable: "{{ pip_bin | default('pip') }}"
      register: pkg_result
      until: pkg_result is success
- name: Virtualenv pip3
  when: volatility_virtualenv | string
  block:
    - name: Ensure virtualenv is present
      ansible.builtin.package:
        name: "{{ python_virtualenv_pkg | default('python-virtualenv') }}"
        state: present
      register: pkg_result
      until: pkg_result is success
    - name: Install volatility3 pip dependencies - virtualenv
      ansible.builtin.pip:
        name: "{{ ['setuptools', 'pip'] + volatility3_pip_pkg }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: Install volatility3 - virtualenv
      ansible.builtin.pip:
        name: "{{ pip_url }}"
        version: "{{ _volatility_release | default(omit) }}"
        state: present
        virtualenv: "{{ volatility_virtualenv }}"
        virtualenv_python: "{{ python_bin | default('python') }}"
      register: pkg_result
      until: pkg_result is success

    - name: Symlink volatility in usual path
      ansible.builtin.file:
        src: "{{ volatility_virtualenv }}/bin/vol"
        dest: "{{ vol_bin_path }}"
        mode: '0755'
        state: link

    - name: Ensure symbols directory writable by all users
      ansible.builtin.file:
        path: "{{ volatility_virtualenv }}/lib/python3.8/site-packages/volatility3/symbols/windows"
        state: directory
        mode: '1777'

- name: Ensure git is present
  ansible.builtin.package:
    name: git
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Import volatility3-modules
  ansible.builtin.import_tasks: volatility3-modules.yml
